name: Publish

on:
  push:
    meta:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Get Release Info
        id: releaser
        run: |
          version=$(echo ${GITHUB_REF} | sed -e "s%refs/meta/%%g")
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Install and Build
        run: yarn && yarn build

      - name: Test Setup
        id: meta
        uses: ./

      - name: Assert
        shell: bash
        run: |
          echo "meta: ${{ steps.meta.outputs.meta }}"
        
      # Compile dist/index.js and bundle with action.yml
      # Force push major and minor meta, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: ${{ steps.releaser.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
